# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5316275a2be1ce8f7619937723f1e65be844c9aea8482e2d039f733a9b5ccd35f3eb25ed71b2b497057bc69ff5d7037c2c227fc804178a12f9ac81011d3b10d6

test:
  secret_key_base: 9aeff411d21804a02c14cb0ce06100b2f023e3601ce9e22a2927e424afb40af24200d251d1e80f041859e8dea818c7e57b5efc29ef7417b0f9c85bd95e5e1276

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
